version: "3.8"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "zhskalComplexPass12"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1434"
    volumes:
      - ebay_auction_data:/var/opt/mssql

  api:
    image: ebay_auction_api_image:latest
    container_name: ebay_auction_api_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7068:7068"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=master;User=sa;Password=zhskalComplexPass12;
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/ebayauction.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=ebaypass

volumes:
  ebay_auction_data:
